name: all_action
'on':
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  all_process: # 处理所有数据
    runs-on: windows-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16 # This line was updated to use Node.js 16

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB_2 }} # Use your personal access token
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run code 
        run: |
          python ./code/craw_data.py
          
        continue-on-error: true

      - name: Commit and push
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "updated"
          git push
